### ISSUE TITLE
hi, do you have the plan to render pdf on vello?  

### ISSUE THREAD

**Issue by videni** [pdf-rs/pdf_render#25]
The pathfinder seems not well maintained for years, Vello looks like the future, I am wondering if you plan to do this job.

**Comment by s3bk** [comment]
Yes I have! It just that it needs time and I totally lack any free time.
I already started it halfway but it needs some more work.

**Comment by videni** [comment]
@s3bk Would you like to share what you have done?  I’d like to contribute. You just need to add the to-dos, and I will implement the details.

**Comment by s3bk** [comment]
I pushed my code to https://github.com/pdf-rs/pdf_render/tree/vello
After tomorrow should be able to find an hour to write the to-dos for you.

**Comment by videni** [comment]
@s3bk  got it , thanks for quick action.

**Comment by videni** [comment]
Close as  it is implmented in this [PR](https://github.com/pdf-rs/pdf_render/pull/26)
