### ISSUE TITLE
cargo run error

### ISSUE THREAD

**Issue by ihoey** [pdf-rs/pdf_render#6]
error[E0432]: unresolved import `winit::platform::unix`
  --> /Users/ihoey/.cargo/git/checkouts/pathfinder_view-e3bb902cdb8b6e4b/559f5cc/src/show.rs:13:58
   |
13 | use winit::platform::{run_return::EventLoopExtRunReturn, unix::EventLoopExtUnix};
   |                                                          ^^^^ could not find `unix` in `platform`

error[E0599]: no function or associated item named `new_any_thread` found for struct `EventLoop<_>` in the current scope
  --> /Users/ihoey/.cargo/git/checkouts/pathfinder_view-e3bb902cdb8b6e4b/559f5cc/src/show.rs:78:37
   |
78 |     let mut event_loop = EventLoop::new_any_thread();
   |                                     ^^^^^^^^^^^^^^ function or associated item not found in `EventLoop<_>`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `pathfinder_view` due to 2 previous errors

**Comment by s3bk** [comment]
Looks like you are not using linux?

You would have to change this: https://github.com/s3bk/pathfinder_view/blob/559f5ccf2f1cf8647d9f3e75a204ad8d38f30376/src/show.rs#L82

And probably a few other places...
