### ISSUE TITLE
spaces aren't written to TextSpan: text

### ISSUE THREAD

**Issue by balenamiaa** [pdf-rs/pdf_render#9]
https://github.com/pdf-rs/pdf_render/blob/29c268f0e1c8ed3217565a43431dc3fee79c1ee0/render/src/textstate.rs#L138-L143

I presume a `span.text.push(' ');` is missing here. Adding it fixes the lack of spaces for me, but I am not sure if its the correct way.

**Comment by s3bk** [comment]
I can add it there and it will work for most files, but not for all. Some creators use kerning for spaces...
